### PR TITLE
Added tests for errors caught looking up runnable scopes.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by geoffjentry** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/164/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by cjllanwarne** [comment]
ToL could this be a WDL4S unit test? Looks like we just need to make sure that creating a namespace from that WDL returns a `Failure` instead of a `Success`?

**Comment by cjllanwarne** [comment]
👍 regarding testing this so we don't regress. I'm still not convinced that Centaur's send-a-workflow-await-a-status is the right way to do it but I'll leave that up to you

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/164/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by kshakir** [comment]
This could be a wdl4s unit test, if wdl4s was throwing errors on these WDLs. For now, cromwell+centaur are making sure that we don't leave the workflow in an infinite `Running` state when tripping over these two known unhandled-by-wdl4s errors.

Filed:
- https://github.com/broadinstitute/wdl4s/issues/92
- https://github.com/broadinstitute/wdl4s/issues/93

**Pull request merged**
