### PR TITLE
yes restart

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/224/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by geoffjentry** [comment]
Oui recommencer

👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/224/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by Horneth** [comment]
@geoffjentry Did you google recommencer or did you know ? :p

**Comment by geoffjentry** [comment]
@Horneth What's french for ¯\_(ツ)_/¯?

**Comment by Horneth** [comment]
@geoffjentry It's "I did google it"

**Comment by geoffjentry** [comment]
@Horneth that's funny how that phrase means something totally different in English :)

**Comment by cjllanwarne** [comment]
I thought it was '[bof](https://en.wiktionary.org/wiki/bof#French)'?

**Comment by Horneth** [comment]
@cjllanwarne Haha yeah I hadn't though of that ! That's actually probably as close as it gets to ¯_(ツ)_/¯

**Comment by Horneth** [comment]
@geoffjentry @mcovarr So apparently the scala `destroy` method on a process kills the JVM in a way that doesn't trigger shutdown hooks...
There's no guarantee that the Java one does either, but in practice it does at least with our current JVM / environment setup.
So I added a commit that switches to that - the alternative is to do something more like @kshakir did in the SFS backend and shell out the process in background, record the PID, and shell out a `kill` to terminate it. There'll also be an improved process API in Java 9 which has a `getPid` method but we're not there yet http://www.javaworld.com/article/3176874/java-language/java-9s-other-new-enhancements-part-3.html

**Comment by geoffjentry** [comment]
@Horneth Fine by me. Let's keep an eye on it though and if it too seems flakey let's revisit.

**Pull request merged**
