### PR TITLE
Fix lots_of_inputs.wdl.  Closes #956

### PR DESCRIPTION
**Pull request by scottfrazer**

### CODE REVIEW

**Comment by scottfrazer** [comment]
Wheel chooses: @mcovarr and @kshakir

**Comment by mcovarr** [comment]
Shouldn't there be changes to the `.test` to remove the `inputs`, and then the `.inputs` should be removed?

**Comment by scottfrazer** [comment]
yes, you're right

**Comment by scottfrazer** [comment]
there we go

**Comment by cjllanwarne** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/61/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/61/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Pull request merged**
