### PR TITLE
Removed "sleep 2" now that cromwell uses `sync`

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by ruchim** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/158/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by geoffjentry** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/158/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by cjllanwarne** [comment]
ToL: 0-10, how confident are we that sync has really fixed this?

**Comment by geoffjentry** [comment]
@cjllanwarne Let's find out. Either way even if the sleeps were doing something it wasn't a good thing for us to have done.

**Comment by kshakir** [comment]
I'm at 9 confidence. The definition of the `sync` command is _exactly_ what we've been looking for. Rebasing and merging.

**Pull request merged**
