### PR TITLE
Doc changes, including optionalTestPath

### PR DESCRIPTION
**Pull request by cjllanwarne**

### CODE REVIEW

**Comment by geoffjentry** [comment]
💯  / (💯  \* 💯 )

👍  

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/83/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by ruchim** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/83/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by cjllanwarne** [comment]
@geoffjentry so... you're saying that this PR is so good, it belongs in the 1%?

**Comment by geoffjentry** [comment]
@cjllanwarne It's the Boris Johnson of PRs

**Pull request merged**
