### PR TITLE
Remove old style metadata files

### PR DESCRIPTION
**Pull request by geoffjentry**

### CODE REVIEW

**Comment by mcovarr** [comment]
does this mean centaur will no longer work against hotfix?

**Comment by geoffjentry** [comment]
The two are completely unrelated

**Comment by cjllanwarne** [comment]
This seems to be removing the links but not the `.metadata` files themselves? Is that right?

**Comment by geoffjentry** [comment]
@cjllanwarne the files were already removed, i just missed this crap previously

**Comment by cjllanwarne** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/49/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by ruchim** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/49/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Pull request merged**
