### PR TITLE
Added docker to tasks that didn't specify it.

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Comment by mcovarr** [comment]
oops :+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by ruchim** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/136/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by cjllanwarne** [comment]
This makes me doubt whether our "continue on return code" test is actually very good...

**Comment by kshakir** [comment]
Always room for improvement ;)

**Pull request merged**
