### PR TITLE
Automated Centaur deployment updates

### PR DESCRIPTION
**Pull request by coreone**
* Add a basic Dockerfile so we can make this into a Docker image
* Add docker-compose files for JES and local backends
* Add Consul template file for pulling Google Service account from Vault
* Add centaur.sh script as an example of how to run Centaur

### CODE REVIEW

**Comment by coreone** [comment]
@hjfbynara can you take a look at this and let me know if there are any issues.  If not, it seems to be working, so we can probably merge it.

**Comment by hjfbynara** [comment]
👍

**Comment by ruchim** [comment]
spoke to Jeff, this is good to merge!

**Comment by ruchim** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/30/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Pull request merged**
