### PR TITLE
update failure metadata path

### PR DESCRIPTION
**Pull request by cjllanwarne**
Additional apologies to @Horneth. I merged your cromwell branch too soon so I'm reverting this one too 😕

### CODE REVIEW

**Comment by Horneth** [comment]
This is a chicken and egg problem, as this PR https://github.com/broadinstitute/cromwell/pull/1102 needs this update to pass Travis, but merging this would fail all other builds not rebased on top of the cromwell PR. 
I don't know how we want to handle these situations.
I ignored those 2 tests and manually made sure they work on the cromwell branch so if we merge this centaur PR, the cromwell PR could go green and we can merge it, after which we could un-ignore those 2 tests...

**Comment by geoffjentry** [comment]
@Horneth IMO as long as people are aware of the situation and the person w/ the PR has done as much as they can manually to verify it's fine to go ahead and push stuff in. If things blow up we can revert

**Comment by cjllanwarne** [comment]
Sounds like a good plan to me 👍 

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/86/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Comment by mcovarr** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/broadinstitute/centaur/pull-request/86/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=broadinstitute/centaur)

**Pull request merged**
